-- Post templates for social media image generation
CREATE TABLE IF NOT EXISTS post_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('resultado_hero', 'agenda_hero', 'resultados_lista', 'agenda_lista', 'gameday', 'capa_resultados', 'capa_agenda', 'custom')),
    background_url TEXT NOT NULL,
    fields JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE post_templates ENABLE ROW LEVEL SECURITY;

-- Anyone can read templates
CREATE POLICY "Public read access" ON post_templates FOR SELECT USING (true);

-- Scheduled posts for future Meta API automation
CREATE TABLE IF NOT EXISTS scheduled_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_slug TEXT,
    template_id BIGINT REFERENCES post_templates(id),
    caption TEXT,
    image_url TEXT,
    scheduled_for TIMESTAMP WITH TIME ZONE,
    posted_at TIMESTAMP WITH TIME ZONE,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'scheduled', 'posted', 'failed')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE scheduled_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read access" ON scheduled_posts FOR SELECT USING (true);
