-- Push notification subscriptions for Web Push API
-- Each user can have multiple subscriptions (one per device/browser)
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,
    endpoint TEXT NOT NULL,
    p256dh TEXT NOT NULL,
    auth TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(user_id, endpoint)
);

-- Row Level Security
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Users can read their own subscriptions
CREATE POLICY "Users read own subscriptions" ON push_subscriptions
    FOR SELECT USING (auth.jwt() ->> 'sub' = user_id);

-- Users can insert their own subscriptions
CREATE POLICY "Users insert own subscriptions" ON push_subscriptions
    FOR INSERT WITH CHECK (auth.jwt() ->> 'sub' = user_id);

-- Users can delete their own subscriptions
CREATE POLICY "Users delete own subscriptions" ON push_subscriptions
    FOR DELETE USING (auth.jwt() ->> 'sub' = user_id);

-- Index for quick lookup by user
CREATE INDEX IF NOT EXISTS idx_push_subscriptions_user ON push_subscriptions(user_id);
